#!/usr/bin/env bash
set -e

WORKDIR=$(mktemp -t temp.XXXXXX)
rm "$WORKDIR"
mkdir "$WORKDIR"
__cleanup () {
    rm -rf "$WORKDIR"
}
trap __cleanup EXIT

php -v

(
    cd "$WORKDIR"

    if php -v | head -1 | grep 'PHP 5.6' > /dev/null; then
        git clone https://github.com/tototoshi/runkit.git
        (
            cd runkit
            git co origin/php5.6
        )
    else
        git clone https://github.com/zenovich/runkit.git
    fi

    (
        cd runkit
        CFLAGS="-Wno-error=unused-function -Wno-error=int-conversion" pecl install package.xml
    )

    INI_FILE_DIR=$(php --ini | grep 'Configuration File (php.ini) Path' | perl -pe 's/.+://g' | tr -d ' ')
    INI_FILE_PATH="$INI_FILE_DIR/php.ini"

    if ! grep runkit.so "$INI_FILE_PATH" > /dev/null 2>&1; then
        echo 'extension="runkit.so"' >> "$INI_FILE_PATH"
    fi
)
